// SPDX-License-Identifier: SEE LICENSE IN LICENSE
pragma solidity ^0.8.9;

contract MyContract{
uint256 public shouldAlwaysBeZero=0;
// public state variables automatically get a getter function generated by the compiler.
uint256  private hiddenValue=0;

function doStuff(uint256 data) public{
// if (data==7){
// shouldAlwaysBeZero=1;
// }
if (hiddenValue==7){
shouldAlwaysBeZero=1;
}
hiddenValue=data;
}

}

// Declares a state variable.

// Generates a function with the same name:

// solidity
// function shouldAlwaysBeZero() external view returns (uint256) {
//     return shouldAlwaysBeZero;
// }